### PR TITLE
configure ML plugin actions

### PR DESCRIPTION
**Pull request by ylwu-amzn**
Signed-off-by: Yaliang Wu <ylwu@amazon.com>

### Description
Add ML plugin actions.

### Category
New feature

### Why these changes are required?
We will release ML plugin in 1.3.

### Testing
Tested on local single node cluster and on multi-node cluster on EC2.

### Check List
- [x] New functionality includes testing
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by davidlago** [comment]
We have already cut a 1.3 branch. If this is tagged as 1.3.0 it should be backported to it. We have the workflow to auto create backport PRs so we could try it here :) adding the appropriate tag, let's see :)

**Review by davidlago — APPROVED** [review]

**Comment by davidlago** [comment]
... or not :) I was thinking of the backend security plugin. This one is still on 1.x in main.

**Comment by ylwu-amzn** [comment]
@peternied @davidlago I don't see backport PR. I can't edit "Labels" to add "backport 1.3", should I publish backport PR manually?

**Comment by davidlago** [comment]
No need to backport. Main is effectively 1.3

**Comment by cliu123** [comment]
Ok. I thought 1.3 branch was needed, therefore, I created 1.3 branch. But looks like 1.3 branch is not needed at this point. I'll delete the 1.3 branch and it can be created when needed.

**Comment by davidlago** [comment]
Apologies... I didn't know you had created it already @cliu123. Yeah, ideally we should start moving to the [project's overall branching strategy](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#branching)

**Comment by cliu123** [comment]
@davidlago No worries. It actually make more sence to create the 1.3 branch when it is needed. The 1.3 branch is indeed not needed at this point. 
I have deleted the 1.3 branch.

**Pull request merged**
