### PR TITLE
Run `cypress-tests` and `cypress-tests-tenancy-disabled` on Chrome

### PR DESCRIPTION
**Pull request by cwperks**
### Description

Fixes an error seen on cypress tests runs like [this](https://github.com/cwperks/security-dashboards-plugin/actions/runs/7426340976/job/20209864738):

```
...
Still waiting to connect to Firefox, retrying in 1 second (attempt 58/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 59/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 60/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 61/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 62/62)
Cypress failed to make a connection to Firefox.

This usually indicates there was a problem opening the Firefox browser.

Error: could not find CRI target
    at lazyAssLogic (/home/runner/.cache/Cypress/9.5.4/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14)
    at lazyAss (/home/runner/.cache/Cypress/9.5.4/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28)
    at findStartPage (/home/runner/.cache/Cypress/9.5.4/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

by switching these workflows to run with Chrome instead.

Also renames these jobs since `tests` is used in multiple workflows and these should ideally be unique.

### Category

Test fix

### Issues Resolved

- https://github.com/opensearch-project/security-dashboards-plugin/issues/1599

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
@cwperks Could you create a copy of this PR in your fork with 10x runs of these jobs to make sure they are reliable?

**Comment by cwperks** [comment]
@peternied I just pushed a [branch](https://github.com/cwperks/security-dashboards-plugin/tree/run-all-cypress-tests-10x) to run this 10x

**Comment by cwperks** [comment]
@peternied See results of the run here: https://github.com/cwperks/security-dashboards-plugin/actions/runs/7448743565/job/20263781185

Ubuntu appears stable, but the windows runners do not consistently pass (its a coin toss).

Should I remove `windows-latest` from the matrix for these checks and file an issue around enabling these 2 checks on Windows?

**Comment by peternied** [comment]
> Should I remove windows-latest from the matrix for these checks and file an issue around enabling these 2 checks on Windows?

Definitely, lets create a separate issue, or add onto an existing one to track what isn't working with windows.

**Comment by cwperks** [comment]
Thank you @peternied. I removed `windows-latest` from the matrix and will modify the description of this issue to include the 2 workflows in this PR.

**Review by peternied — DISMISSED** [review]

**Review by DarshitChanpura — DISMISSED** [review]

**Review by derek-ho — APPROVED** [review]
LGTM

**Review by RyanL1997 — APPROVED** [review]

**Review by DarshitChanpura — APPROVED** [review]

**Pull request merged**
