### PR TITLE
Refactor login logo usage

### LINKED ISSUE #1529: (OUI Next Theme) Log in
_This issue to be transferred to corresponding repository_

I am working on launching new light and dark mode themes provided by [OUI component library](https://oui.opensearch.org/1.2/#/) for a target launch within 2.10. These changes support the vision expressed in [Future Vision for Dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4298.)

I have identified the following front end related issues that prevent the theme from appearing complete and potential solutions within this feature:

- [x] Log in page should reflect theme set by admin (`v7 light`, `v7 dark`, `next light`, `next dark`) 
- [x] When theme is set to `Next Dark` or `v7 dark` by admin, Auto-filled text appears illegible. Auto filled text should not receive a different styling treatment as manually entered text. 
- [ ] When theme is set to `Next Dark` or `v7 dark` by admin, OpenSearch logo should display dark mode variant (currently showing light mode variant in dark mode theme)
Screen Shot 2023-07-31 at 2 55 53 PM

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description
This change uses the imagery exposed by OSD for the login screen.

### Issues Resolved
#1529

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by cwperks — DISMISSED** [review]
@AMoo-Miki This change looks good to me. The failing integ tests are unrelated to this change and currently being worked on: https://github.com/opensearch-project/security/pull/3272

**Comment by cwperks** [comment]
@AMoo-Miki Can you address the failing unit tests?

>   ● Login page › handle submit event › submit click event

    TypeError: Cannot read properties of undefined (reading 'logos')

      260 |           size="fullWidth"
      261 |           alt=""
    > 262 |           url={props.config.ui.basicauth.login.brandimage || props.chrome.logos.OpenSearch.url}
          |                                                                           ^
      263 |         />
      264 |       )}
      265 |       <EuiSpacer size="s" />

**Comment by peternied** [comment]
@AMoo-Miki Do you want to get this in for 2.10? The window is closing in pretty fast

**Comment by cwperks** [comment]
@peternied This is blocked by https://github.com/opensearch-project/security/pull/3278

Once the security PR is merged I will re-run the CI

**Review by cwperks — APPROVED** [review]

**Comment by peternied** [comment]
Issue from the security plugin has been merged into main [1], I've retriggered the integration tests.

- [1] https://github.com/opensearch-project/security/pull/3278

**Review by scrawfor99 — APPROVED** [review]

**Pull request merged**
