### PR TITLE
Fixes Short URL redirection for SAML login

### LINKED ISSUE #1627: [BUG] 1.3.12 Short URL raises 400 error during SAML login
**What is the bug?**

When opening a short URL pointing to a SAML-enabled OSD instance the SAML login flow won't be initiated and clients will receive the following response:

```
{"statusCode":400,"error":"Bad Request","message":"[request query.security_tenant]: definition for this key is missing"}
``` 

What's interesting is that the `nextURL` won't include the HTTP-encoded `security_tenant` parameter.
Instead, an empty `security_tenant` parameter will be included in the request itself.

For example, opening the short URL

```
http://localhost:5601/goto/3eb6108934e0f3208a0f7f0afe0c69c5?security_tenant=global
```

will redirect the client to 

```
http://localhost:5601/goto/3eb6108934e0f3208a0f7f0afe0c69c5?security_tenant=global
auth/saml/captureUrlFragment?nextUrl=%2Fgoto%2F3eb6108934e0f3208a0f7f0afe0c69c5&security_tenant=
```

Verbose flow using `curl`:

```
$ curl 'http://localhost:5601/goto/3a572e1e320b3486e9708efa9dce0a2f?security_tenant=global' -vL
*   Trying 127.0.0.1:5601...
* Connected to localhost (127.0.0.1) port 5601 (#0)
> GET /goto/3a572e1e320b3486e9708efa9dce0a2f?security_tenant=global HTTP/1.1
> Host: localhost:5601
> User-Agent: curl/8.0.1
> Accept: */*
> 
< HTTP/1.1 302 Found
< location: /auth/saml/captureUrlFragment?nextUrl=%2Fgoto%2F3a572e1e320b3486e9708efa9dce0a2f&security_tenant=
< set-cookie: security_authentication=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT; HttpOnly; Path=/
< set-cookie: security_authentication=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT; HttpOnly; Path=/
< osd-name: kibana-deployment-5584d77474-dgwzp
< cache-control: private, no-cache, no-store, must-revalidate
< content-length: 0
< Date: Sat, 21 Oct 2023 10:03:33 GMT
< Connection: keep-alive
< 
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost:5601/auth/saml/captureUrlFragment?nextUrl=%2Fgoto%2F3a572e1e320b3486e9708efa9dce0a2f&security_tenant='
* Found bundle for host: 0x10a4100 [serially]
* Can not multiplex, even if we wanted to
* Re-using existing connection #0 with host localhost
> GET /auth/saml/captureUrlFragment?nextUrl=%2Fgoto%2F3a572e1e320b3486e9708efa9dce0a2f&security_tenant= HTTP/1.1
> Host: localhost:5601
> User-Agent: curl/8.0.1
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< osd-name: kibana-deployment-5584d77474-dgwzp
< content-type: application/json; charset=utf-8
< cache-control: private, no-cache, no-store, must-revalidate
< content-length: 120
< Date: Sat, 21 Oct 2023 10:03:33 GMT
< Connection: keep-alive
< 
* Connection #0 to host localhost left intact
{"statusCode":400,"error":"Bad Request","message":"[request query.security_tenant]: definition for this key is missing"}
```

**How can one reproduce the bug?**

1. Set up a SAML enabled OSD instance
2. Log in to the instance
3. Create a short URL in the global tenant
4. Log out of your OSD instance
5. Open the short URL
6. See error

**What is the expected behavior?**

I expected the SAML login flow to be triggered with the correct `nextURL`.

**What is your host/environment?**
- Client: macOS Sonoma 14.0, Chrome 118.0.5993.88 (arm64), curl 8.0.1 (x86_64-koji-linux-gnu)
- Server:  Kubernetes 1.25.12, workers using gardenlinux 934.10.0, pods using opensearchproject/opensearch-dashboards:1.3.12 (Amazon Linux 2)
- Plugins: Security Dashboards Plugin

**Do you have any screenshots?**
Not applicable

**Do you have any additional context?**

Obviously, authenticated clients will not be affected. One can work around the issue by HTTP-encoding the `security_tenant` parameter and appending it to the value of `nextURL` to properly trigger the SAML login flow manually:

```
$ curl -vL 'http://localhost:5601/auth/saml/captureUrlFragment?nextUrl=%2Fgoto%2F3eb6108934e0f3208a0f7f0afe0c69c5%3Fsecurity_tenant%3Dglobal'
*   Trying 127.0.0.1:5601...
* Connected to localhost (127.0.0.1) port 5601 (#0)
> GET /auth/saml/captureUrlFragment?nextUrl=%2Fgoto%2F3eb6108934e0f3208a0f7f0afe0c69c5%3Fsecurity_tenant%3Dglobal HTTP/1.1
> Host: localhost:5601
> User-Agent: curl/8.0.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< content-security-policy: script-src 'unsafe-eval' 'self'; worker-src blob: 'self'; style-src 'unsafe-inline' 'self'
< osd-name: kibana-deployment-5584d77474-dgwzp
< cache-control: private, no-cache, no-store, must-revalidate
< set-cookie: security_authentication=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT; HttpOnly; Path=/
< content-length: 196
< accept-ranges: bytes
< Date: Sat, 21 Oct 2023 10:27:19 GMT
< Connection: keep-alive
< 

            <!DOCTYPE html>
            <title>OSD SAML Capture</title>
            <link rel="icon" href="data:,">
            <script src="/auth/saml/captureUrlFragment.js"></script>
* Connection #0 to host localhost left intact
          
``` 

I have a hunch that the `generateNextURL` function simply drops all parameters because it only takes into account the `request.url.pathname` without parameters: https://github.com/opensearch-project/security-dashboards-plugin/blob/1.3.12.0/server/auth/types/saml/saml_auth.ts#L54-L59

This could be wrong though because the problem seems to affect short URLs only (or any tenant-scoped resource, I didn't test this yet). I couldn't test this claim though because I had problems running the unit tests for the project.

### PR DESCRIPTION
**Pull request by devardee**
### Description
Resolves a bug where SAML endpoints login flow was broken when attempted to login via short url.

### Category
 Bug fix

### Why these changes are required?
To allow short urls to work successfully for SAML SSO logins.

### What is the old behavior before changes and new behavior after changes?
Old: Short URL would throw 400 when try to initiate login for SAML endpoints
New: Short URL redirects to SAML login properly

### Issues Resolved
- Resolves #1627 

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [x] New functionality includes testing
~- [ ] New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

cc: @anijain-Amazon

### CODE REVIEW

**Review by peternied — DISMISSED** [review]
Thanks for the contribution, lets update the saml test cases to make sure this scenario is handled correctly with this change.

**Comment by DarshitChanpura** [comment]
@devardee to add to @peternied's comment, could you please update the PR title/description to be more detailed?

**Comment by devardee** [comment]
> lets update the saml test cases to make sure this scenario is handled correctly with this change.

@peternied can you please guide me on what kind of testing needs to be added here ?

@DarshitChanpura the linked GH issue is very descriptive, can I copy/paste from there ?

**Comment by devardee** [comment]
I see there are end-to-end tests [here](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/test/cypress/e2e/saml/saml_auth_test.spec.js), however, I am unable to run them locally, can the team pls help me on setting up my IDE, so that I can added new tests

**Comment by cwperks** [comment]
@devardee To run those tests:

1. Create a local distribution of core and install the security plugin with the demo configuration
2. Replace the demo configuration's config.yml with the config.yml in this [workflow](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/.github/workflows/cypress-test-saml-e2e.yml).
3. Start OpenSearch
4. Clone OSD and also clone the security-dashboards-plugin in the plugins folder of OSD
5. Configure config/opensearch_dashboards.yml with the values present in this [workflow](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/.github/workflows/cypress-test-saml-e2e.yml)
6. Start Dashboards
7. In a third terminal window navigate to OpenSearch-Dashboards/plugins/security-dashboards-plugin and run the command from this [line](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/.github/workflows/cypress-test-saml-e2e.yml#L101): `yarn cypress:run --browser chrome --headless --spec "test/cypress/e2e/saml/*.js"`

**Comment by DarshitChanpura** [comment]
> @DarshitChanpura the linked GH issue is very descriptive, can I copy/paste from there ?

I've made changes to the description. Feel free to correct if anything is missing.

**Comment by devardee** [comment]
@peternied , @DarshitChanpura  I have added IT. Please take a look

**Comment by devardee** [comment]
the newly added test is failing in multi-auth test workflow 😔, can anyone please help me out on why that particular test is failing. 

Not able to understand the failure from logs :

```
AssertionError: expected null to exist
      at Context.eval (webpack://opensearch-security-dashboards/./test/cypress/e2e/saml/saml_auth_test.spec.js:134:46)
```

**Comment by cwperks** [comment]
@devardee I made some slight modifications to the test to first login, then to use `cy.request` instead of `cy.visit` like this:

```
it.only('Login to Dashboard with Goto URL', () => {
  localStorage.setItem('home:newThemeModal:show', 'false');

  cy.visit('http://localhost:5601/app/opensearch_dashboards_overview', {
    failOnStatusCode: false,
  });

  samlLogin();

  cy.shortenUrl(SHORTEN_URL_DATA, 'global').then((response) => {
    const gotoUrl = `http://localhost:5601/goto/${response.urlId}?security_tenant=global`;
    cy.request(gotoUrl);
    cy.getCookie('security_authentication').should('exist');
  });
});
```

`cy.request` will make a request to the shortened URL using the cookies currently stored in the browser and those cookies are set in the browser after login.

**Comment by devardee** [comment]
@cwperks , thanks for the help 😊. All the tests passed locally. Hope it pass in the github CI as well

**Comment by cwperks** [comment]
@devardee Did you try the suggestion from this [comment](https://github.com/opensearch-project/security-dashboards-plugin/pull/1744#issuecomment-1919400147)? Login first, then navigate to shortUrl?

**Comment by devardee** [comment]
Hi Team, pls take a look, github ci has passed

cc: @cwperks

**Review by DarshitChanpura — APPROVED** [review]
LGTM. Thanks @devardee !

**Review by cwperks — APPROVED** [review]

**Review by scrawfor99 — APPROVED** [review]
Great job!

**Comment by wbeckler** [comment]
It would be awesome if this could make it into 2.12

**Pull request merged**
