### PR TITLE
Run release time FTR tests on PR runs

### PR DESCRIPTION
**Pull request by derek-ho**
### Description
This PR adds running all the associated FTR tests on every PR getting merged into the security dashboards plugin. This will raise awareness of the implicit connection here, and also let contributors know when their change needs to make a corresponding test in the FTR, instead of waiting until release time to figure this out. 

### Category
Enhancement
### Why these changes are required?
Fix: #1936 

### What is the old behavior before changes and new behavior after changes?
Before: not all FTR tests were being run
After: now, all tests run during release time are run with every raised PR

### Issues Resolved
Close: #1936 
### Testing
Existing tests pass
### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by derek-ho** [comment]
Looks like it may just be timing out I need to double check this

**Review by RyanL1997 — APPROVED** [review]

**Review by DarshitChanpura — APPROVED** [review]

**Comment by derek-ho** [comment]
Blocked on: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7154

**Comment by RyanL1997** [comment]
The fix for the above issue is here: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7163

**Comment by RyanL1997** [comment]
Fix got merged, and re-running all the CI jobs

**Comment by cwperks** [comment]
@derek-ho do we need to complete https://github.com/opensearch-project/security-dashboards-plugin/issues/2005 and associated reversion in FTR to avoid this state where main shows one label and 2.x shows a separate label?

**Review by DarshitChanpura — COMMENTED** [review]
Changes in this commit are causing the tests to fail: https://github.com/opensearch-project/opensearch-dashboards-functional-test/commit/6cba7a6b3cff3633055b4a0cedb2bd34bdc52870

**Comment by DarshitChanpura** [comment]
this PR should fix cypress test failure: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1439 and unblock CI

**Review by DarshitChanpura — APPROVED** [review]

**Review by scrawfor99 — APPROVED** [review]

**Review by cwperks — APPROVED** [review]

**Pull request merged**
