### PR TITLE
[Backport 1.x] Switch to new tenant after loading a copied long URL (#1450)

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description
Backports 7f4e0f29f11668b09c5343da2cbc97ac1d6d0acf from #1450 

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
@DarshitChanpura Could you provide a reason why the manual backport was needed?

**Comment by DarshitChanpura** [comment]
> @DarshitChanpura Could you provide a reason why the manual backport was needed?

Yes. Auto backport to 1.x failed: https://github.com/opensearch-project/security-dashboards-plugin/pull/1462#issuecomment-1638212557

**Comment by peternied** [comment]
Could you provide details on what conflict had to be handled, should another backport be included for this change?

**Comment by peternied** [comment]
Should be unblocked after https://github.com/opensearch-project/security-dashboards-plugin/pull/1521 has been merged and this pull request is rebased

**Review by peternied — APPROVED** [review]

**Pull request merged**
