### PR TITLE
Provide ability to view password

### PR DESCRIPTION
**Pull request by derek-ho**
### Description
Previously, there is no way to view the password that a user types when creating a user or resetting the password. This could be frustrating if the password is long and cannot be updated without retyping the whole thing. This PR adds that ability. 

### Category
Enhancement
### Why these changes are required?
To improve the user experience

### What is the old behavior before changes and new behavior after changes?

https://github.com/opensearch-project/security-dashboards-plugin/assets/26328171/c71df760-f87b-4329-adc9-1c23ddb6f3b5

### Issues Resolved
Fix: https://github.com/opensearch-project/security-dashboards-plugin/issues/1940
### Testing
Snapshot test, video
### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by cwperks — APPROVED** [review]

**Comment by derek-ho** [comment]
Blocked on: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6878

**Review by DarshitChanpura — COMMENTED** [review]
Thanks @derek-ho ! While you wait to get unblocked, what do you think about adding this feature to login screen as well for basic-auth?

**Comment by derek-ho** [comment]
Thanks that is a good suggestion - here is how it looks with the new addition on the login screen

Screenshot 2024-05-31 at 12 41 59 PM

**Comment by cwperks** [comment]
@derek-ho updated the branch protection rules. main now matches 2.*. There was an issue where Unit tests for Mac OS were required, but Unit tests for Windows were not. On 2.* it required Unit Tests to run successfully for Windows so I updated the rules on main to match.

**Review by DarshitChanpura — DISMISSED** [review]
LGTM!

**Review by scrawfor99 — APPROVED** [review]

**Review by DarshitChanpura — APPROVED** [review]

**Pull request merged**
