### PR TITLE
Increment version to 1.3.9

### PR DESCRIPTION
**Pull request by RyanL1997**
Signed-off-by: Ryan Liang <jiallian@amazon.com>

### Description
Increment version to 1.3.9
### Category
[Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation]
Maintenance

### Issues Resolved
[List any issues this PR will resolve (Is this a backport? If so, please add backport PR # and/or commits #)]

### Check List
- [ ] ~New functionality includes testing~
- [ ] ~New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — CHANGES_REQUESTED** [review]
```
Location: /ci/dbc/distribution-build-opensearch/1.3.9/7067/windows/x64/zip/builds/opensearch/plugins/opensearch-security-1.3.9.0.zip [following]
--2023-02-10 23:12:30--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.9/7067/windows/x64/zip/builds/opensearch/plugins/opensearch-security-1.3.9.0.zip
Reusing existing connection to ci.opensearch.org:443.
HTTP request sent, awaiting response... 403 Forbidden
2023-02-10 23:12:31 ERROR 403: Forbidden.
```

Looks like we need to fix this build to `latest`, @RyanL1997 can you look into this?

**Comment by RyanL1997** [comment]
> ```
> Location: /ci/dbc/distribution-build-opensearch/1.3.9/7067/windows/x64/zip/builds/opensearch/plugins/opensearch-security-1.3.9.0.zip [following]
> --2023-02-10 23:12:30--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.9/7067/windows/x64/zip/builds/opensearch/plugins/opensearch-security-1.3.9.0.zip
> Reusing existing connection to ci.opensearch.org:443.
> HTTP request sent, awaiting response... 403 Forbidden
> 2023-02-10 23:12:31 ERROR 403: Forbidden.
> ```
> 
> Looks like we need to fix this build to `latest`, @RyanL1997 can you look into this?

@peternied Thanks for the review! I think it is the `latest`: https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/4148396846/jobs/7231566838#step:9:66. The reason we are getting this 403 is that we are still awaiting for the version increment of the security backend and build that artifact. There is no changes need to be applied for this one.

**Comment by peternied** [comment]
@RyanL1997 We can't use maven because the 1.3 security plugin doesn't support publishing to maven https://github.com/opensearch-project/security-dashboards-plugin/pull/1331#issuecomment-1447466775

If you figure out how to get this supported in 1.3 then we can start publishing and consuming via maven.

**Comment by RyanL1997** [comment]
Awaiting for the merge of https://github.com/opensearch-project/opensearch-build/pull/3263, so that we can get the distribution build to unblock this PR

**Comment by RyanL1997** [comment]
@peternied Got it. For this one, we have added the security plugin to the manifest, and the CI is passing. I think we are good to merge this PR now.

**Review by cwperks — APPROVED** [review]

**Review by scrawfor99 — APPROVED** [review]

**Pull request merged**
