### PR TITLE
Change 'Index' to 'Index Pattern' in UX

### PR DESCRIPTION
**Pull request by sudhanshugoel26**
Signed-off-by: sudhanshugoel26 <goyalsudhanshu26@gmail.com>

Add Signoff

Signed-off-by: sudhanshugoel26 <goyalsudhanshu26@gmail.com>

### Description
Signing commit again with DCO check : Change made "Index" to "Index Patterns" in line 74 and 205 

### Category

Bug Fix 

### Issues Resolved
https://github.com/opensearch-project/security-dashboards-plugin/pull/1072#issuecomment-1252080457

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
@RyanL1997 Could you take a look at this?

**Comment by RyanL1997** [comment]
Hi @sudhanshugoel26, thank you for creating this PR. here is the comment from the original issue: https://github.com/opensearch-project/security-dashboards-plugin/pull/1072#issuecomment-1258255154.

**Review by DarshitChanpura — APPROVED** [review]

**Comment by DarshitChanpura** [comment]
@shanilpa Are we to change the column name to `Index Patterns`?

**Comment by shanilpa** [comment]
From a UX perspective the column name in roles which is currently "index permissions" should be the same as the form field label "index" on the role creation screen. Changing "index permissions" to "index" creates this uniformity.

From: 
image

To this:
image

To align with this on the role creation page: 
image

**Comment by RyanL1997** [comment]
Hi @shanilpa, thank you so much for the feedback! I believe PR #1072 has already fixed the inconsistence. I think we can close this PR now.

**Comment by cliu123** [comment]
Thanks for 
The fix in [PR#1072](https://github.com/opensearch-project/security-dashboards-plugin/pull/1072) already fixed the inconsistency between the column namd and the field name. Index includes concrete index name and index patterns. 
I agree that the changes in this PR is not needed. There was a concensus on the fix with our product team. Cc: @jimishs

**Comment by DarshitChanpura** [comment]
Closing this PR following the discussion above.

**Pull request closed without merging**
