### PR TITLE
Removes branch filter on test workflow

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description
Updates unit and integration test workflow to run on all branches rather than just the main branch

### Category
Maintenance

### Why these changes are required?
To run test on all PRs

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by cliu123 — DISMISSED** [review]

**Comment by cliu123** [comment]
ITs failed.

**Comment by DarshitChanpura** [comment]
<details>
<summary>yes...because it is unable to find the latest 1.3.1.0 image for security-plugin:</summary>
```
Run wget -O opensearch-security.zip https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.1/latest/linux/x64/builds/opensearch/plugins/opensearch-security-1.3.1.0.zip
--2022-03-28 18:53:22--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.1/latest/linux/x6[4](https://github.com/opensearch-project/security-dashboards-plugin/runs/5725831115?check_suite_focus=true#step:3:4)/builds/opensearch/plugins/opensearch-security-1.3.1.0.zip
Resolving ci.opensearch.org (ci.opensearch.org)... [5](https://github.com/opensearch-project/security-dashboards-plugin/runs/5725831115?check_suite_focus=true#step:3:5)4.192.192.28, 54.192.192.13, 54.192.192.87, ...
Connecting to ci.opensearch.org (ci.opensearch.org)|54.192.192.28|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: /ci/dbc/distribution-build-opensearch/1.3.1/15[6](https://github.com/opensearch-project/security-dashboards-plugin/runs/5725831115?check_suite_focus=true#step:3:6)1/linux/x64/builds/opensearch/plugins/opensearch-security-1.3.1.0.zip [following]
--2022-03-2[8](https://github.com/opensearch-project/security-dashboards-plugin/runs/5725831115?check_suite_focus=true#step:3:8) 18:53:22--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.1/1561/linux/x64/builds/opensearch/plugins/opensearch-security-1.3.1.0.zip
Reusing existing connection to ci.opensearch.org:443.
HTTP request sent, awaiting response... 403 Forbidden
2022-03-28 18:53:23 ERROR 403: Forbidden.
```
</details>

**Review by peternied — APPROVED** [review]

**Comment by peternied** [comment]
In this change you also need to resolve the bad references in the integration test run for 1.3

**Comment by DarshitChanpura** [comment]
> In this change you also need to resolve the bad references in the integration test run for 1.3

Should I revert the wget commands in the ymls to use 1.3.0.0 instead of 1.3.1.0? Or is it something else that you are pointing to?

**Comment by peternied** [comment]
This change is being merged onto 1.3 and from the error, the 1.3.1 build isn't resolving  as its getting a 403.  How are we planning on fixing this?

```
--2022-03-28 18:53:22--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.1/1561/linux/x64/builds/opensearch/plugins/opensearch-security-1.3.1.0.zip
Reusing existing connection to ci.opensearch.org:443.
HTTP request sent, awaiting response... 403 Forbidden
```

**Comment by peternied** [comment]
> This change is being merged onto 1.3 and from the error, the 1.3.1 build isn't resolving as its getting a 403. How are we planning on fixing this?
> 
> ```
> --2022-03-28 18:53:22--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.1/1561/linux/x64/builds/opensearch/plugins/opensearch-security-1.3.1.0.zip
> Reusing existing connection to ci.opensearch.org:443.
> HTTP request sent, awaiting response... 403 Forbidden
> ```

[Offline] We haven't yet added the security backend changes into the 1.3.1 [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.1/opensearch-1.3.1.yml), after this has been done and a build has been created the URL will start to work.

**Comment by DarshitChanpura** [comment]
> > This change is being merged onto 1.3 and from the error, the 1.3.1 build isn't resolving as its getting a 403. How are we planning on fixing this?
> > ```
> > --2022-03-28 18:53:22--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.1/1561/linux/x64/builds/opensearch/plugins/opensearch-security-1.3.1.0.zip
> > Reusing existing connection to ci.opensearch.org:443.
> > HTTP request sent, awaiting response... 403 Forbidden
> > ```
> 
> [Offline] We haven't yet added the security backend changes into the 1.3.1 [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.1/opensearch-1.3.1.yml), after this has been done and a build has been created the URL will start to work.

Once this PR: https://github.com/opensearch-project/opensearch-build/pull/1840/ gets merged we can re-run the ITs for this branch.

**Comment by DarshitChanpura** [comment]
> > > This change is being merged onto 1.3 and from the error, the 1.3.1 build isn't resolving as its getting a 403. How are we planning on fixing this?
> > > ```
> > > --2022-03-28 18:53:22--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.1/1561/linux/x64/builds/opensearch/plugins/opensearch-security-1.3.1.0.zip
> > > Reusing existing connection to ci.opensearch.org:443.
> > > HTTP request sent, awaiting response... 403 Forbidden
> > > ```
> > 
> > 
> > [Offline] We haven't yet added the security backend changes into the 1.3.1 [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.1/opensearch-1.3.1.yml), after this has been done and a build has been created the URL will start to work.
> 
> Once this PR: [opensearch-project/opensearch-build#1840](https://github.com/opensearch-project/opensearch-build/pull/1840) gets merged we can re-run the ITs for this branch.

PR: #1840 has been merged and I have re-run IT job now

**Comment by DarshitChanpura** [comment]
@cliu123 @peternied can i get your review on this PR?

**Review by davidlago — APPROVED** [review]

**Pull request merged**
