### PR TITLE
[BUG-1427] Newly created user defaults to same tenant as admin when using same browser window.

### PR DESCRIPTION
**Pull request by prabhask5**
### Description
Fixes bug that defaults a new user to the Global tenant, even when they do not have permission for the Global tenant and this option is blocked out on the modal. To fix this, I added a new check to the resolveTenantName function, in which it checks of whether the Global tenant is available for this account through a new parameter to the function, in that case it skips over the Global tenant return and returns a Private tenant.

### Category
Bug fix

### Why these changes are required?
New users were having the Global tenant role even when they don't have the permissions to, which is a security risk.

### What is the old behavior before changes and new behavior after changes?
Old behavior: When you select global tenant on the admin account then switch to a new user, this global tenant is selected by default even when this option is not available since the new user doesn't have access to the Global tenant.
Screenshot 2023-10-18 at 12 40 40 AM

New behavior: In this case, the default option automatically switches to the next accessible role, which is the Private tenant.
Screenshot 2023-10-18 at 12 52 10 AM

### Issues Resolved
Fixed issue #1427 

### Testing
Manually tested to make sure nothing was broken. Additionally added new tests to tenant-utils.test.tsx to update function and test for cases where the global tenant is not enabled.

### Check List
- [x] New functionality includes testing
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cwperks** [comment]
@prabhask5 I have a few general questions.

1. I think its possible that cluster admins can disable the private tenant. In that case how will this PR handle that scenario?

2. Is it ever possible that a user has access to 0 tenants? If so, what is the behavior?

3. If private or global are disabled does this PR resort to the first tenant for which the user has access?

**Comment by cwperks** [comment]
FYI The CI is unstable in this repo atm. There is an open PR to address CI stability: https://github.com/opensearch-project/security-dashboards-plugin/pull/1613

You may need to rebase after merge of that PR to get more accurate CI results.

**Comment by prabhask5** [comment]
Closing to start over on code changes to consider questions asked in PR comments

**Comment by prabhask5** [comment]
> @prabhask5 I have a few general questions.
> 
> 1. I think its possible that cluster admins can disable the private tenant. In that case how will this PR handle that scenario?
> 2. Is it ever possible that a user has access to 0 tenants? If so, what is the behavior?
> 3. If private or global are disabled does this PR resort to the first tenant for which the user has access?

@cwperks I'm not sure on what conditions the global and private tenants are disabled- does this depend on the data in the accountInfo tenantsList or does it depend on other info (either the config global disabled properties or the readonly roles), or both?

I'm also not sure if there's ever a scenario where there is access to 0 tenants- in my new changes I'm allowing the function to return an empty string for tenant, but when I try to do this on my local build that part doesn't work properly- so I'm assuming this can't happen?

**Comment by prabhask5** [comment]
> > @prabhask5 I have a few general questions.
> > 
> > 1. I think its possible that cluster admins can disable the private tenant. In that case how will this PR handle that scenario?
> > 2. Is it ever possible that a user has access to 0 tenants? If so, what is the behavior?
> > 3. If private or global are disabled does this PR resort to the first tenant for which the user has access?
> 
> @cwperks I'm not sure on what conditions the global and private tenants are disabled- does this depend on the data in the accountInfo tenantsList or does it depend on other info (either the config global disabled properties or the readonly roles), or both?
> 
> I'm also not sure if there's ever a scenario where there is access to 0 tenants- in my new changes I'm allowing the function to return an empty string for tenant, but when I try to do this on my local build that part doesn't work properly- so I'm assuming this can't happen?

To additional info, currently I'm using the following checks to see if the global and private tenants are disabled respectively:

`const shouldDisableGlobal = !isGlobalEnabled || !tenants.includes('global_tenant');`
`const shouldDisablePrivate = !isPrivateEnabled || !tenants.includes(userName) || readonly;`

But this is causing some tests to fail as they don't but the private and global tenants in the tenants list so this util function thinks they are disabled when they are not. Am I wrong or are the tests wrong?

**Pull request closed without merging**
