### PR TITLE
Add release notes for 2.12.0.0

### PR DESCRIPTION
**Pull request by cwperks**
### Description

Add release notes for 2.12.0.0 release

### Category

Documentation

### Issues Resolved

- https://github.com/opensearch-project/security-dashboards-plugin/issues/1606

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — APPROVED** [review]

**Review by DarshitChanpura — APPROVED** [review]

**Comment by cwperks** [comment]
Looking into cypress test failure

**Comment by cwperks** [comment]
There may have been a recent change in the saved objects API: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5777

```
  1) Saved objects table test
       "before all" hook for "should check the saved objects as global tenant":
     CypressError: `cy.request()` failed trying to load:

http://localhost:5601/api/saved_objects/index-pattern/index-pattern1
```

**Comment by DarshitChanpura** [comment]
I'm gonna squash and merge as the changes in this PR do not affect Cypress workflow in anyway.

**Comment by peternied** [comment]
> I'm gonna squash and merge as the changes in this PR do not affect Cypress workflow in anyway.

@cwperks @DarshitChanpura Please create a follow up issue since a downstream change has broken our test cases

**Comment by derek-ho** [comment]
#1779

**Comment by derek-ho** [comment]
Doesn't seem like a problem with that API, I am also seeing other failures on other APIs, example: https://github.com/opensearch-project/dashboards-observability/actions/runs/7838604132/job/21390299850

**Pull request merged**
