### PR TITLE
added loginEndPointWithPath

### LINKED ISSUE #1349: [BUG] Setting basePath and auth.multiple_auth_enabled results in the wrong url in the UI
**What is the bug?**
When you set the `server.basePath` to a custom path and also set the `opensearch_security.auth.multiple_auth_enabled` to true (with openid connect) you do not get the correct URL in the UI. The UI keeps the '/auth/openid/login' path instead of adding the custom prefix from  `server.basePath`. 

**How can one reproduce the bug?**
1. set the followin config options:
```
opensearch_security.auth.type: ['basicauth', 'openid']
opensearch_security.auth.multiple_auth_enabled: True
opensearch_security.ui.openid.login.buttonname: Login with Keycloak
opensearch_security.openid.connect_url: https://not_a_real_dns:8300/auth/realms/DEMO/.well-known/openid-configuration
opensearch_security.openid.base_redirect_url: https://not_a_real_dns:5601/dashboards
opensearch_security.openid.client_id: opensearch-dashboards
opensearch_security.openid.client_secret: XXXXXXXXXXXXXXXXXXXXXXX
server.basePath: /dashboards
server.rewriteBasePath: True
```
2. Go to the login page and inspect the 'login with keycloak' button
image

**What is the expected behavior?**
The href for the openid login should include the basePath.

**What is your host/environment?**
 - OS: Ubuntu 20.04
 - Version 2.5.0 (docker)

**Do you have any screenshots?**
Yes, see in the reproduce steps.

**Do you have any additional context?**
After a quick look it looks like [OPENID_AUTH_LOGIN ](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/common/index.ts#L31) is used in [renderLoginButton](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/apps/login/login-page.tsx#L112) without checking the serverBasePath.

### PR DESCRIPTION
**Pull request by mattieserver**
Signed-off-by: Mattijs Vanhaverbeke <mattijs-v@live.be>

### Description
This adds the basepath to the login button when multiple authentication is enabled with openid/saml with a csutom basePath

### Category
Bug fix

### Why these changes are required?
Login button redirects to the wrong location.

### What is the old behavior before changes and new behavior after changes?
Redirects to /auth/XXX instead of basePath/auth/

### Issues Resolved
#1349

### Testing
manual tested

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.IBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
Thanks for this fix @mattieserver could you please add / update a test case to verify this behavior?

**Comment by mattieserver** [comment]
Yes, will try to add some tests this week

**Comment by mattieserver** [comment]
Hi @RyanL1997 & @peternied  ,

It seems like there are already tests that should catch this issue.
The basepath is already set in [login-page.test.tsx](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/apps/login/test/login-page.test.tsx#L68), so i changed the snapshot to reflect this.

Are there any other tests that are needed?

**Comment by RyanL1997** [comment]
Hi @mattieserver, thanks for the follow-up. 
>The basepath is already set in [login-page.test.tsx](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/apps/login/test/login-page.test.tsx#L68), so i changed the snapshot to reflect this.
Are there any other tests that are needed?

Modify the snapshot will be sufficient enough to adapt your change, so at this point this PR is good to be merged imo. Just for your info, we are also working on a OIDC integration test, so that the issues like this can be automatically detected in the future. And I will create a follow up issue on that.

>Also, the only thing i am not sure about is what happens when the basepath is not set.

For this question, based on my experiment, the `server.basePath` will use the default value if it is not get setup. However, if the `base_redirect_url` doesn't setup, it will cause an `Invalid parameter: redirect_uri` error.

Again, thanks for this contribution! I will update the branch and approve this PR.

**Review by RyanL1997 — APPROVED** [review]

**Review by cwperks — APPROVED** [review]

**Pull request merged**
