### PR TITLE
Bump the version of json5 from 1.0.1 to 1.0.2

### PR DESCRIPTION
**Pull request by RyanL1997**
Signed-off-by: Ryan Liang <jiallian@amazon.com>

### Description
Bump the version of json5 from 1.0.1 to 1.0.2
### Category
Maintenance
### Issues Resolved
* Relate https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3148
### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] ~New functionality includes testing~
- [ ] ~New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by RyanL1997** [comment]
This PR is blocked by the version update of 1.3.8. Once the version increment is done I will re-run the integ test.

**Comment by cwperks** [comment]
@RyanL1997 It won't be fixed until the security plugin is incremented to 1.3.8 and added to the build manifest. This PR (https://github.com/opensearch-project/security/pull/2344) needs to be merged, but its currently blocked by failing plugin install workflow which is because the version increment is not being applied to all necessary files.

**Review by peternied — CHANGES_REQUESTED** [review]
Dashboards is still on version 1.0.1 per their package.json in branch `1.3` [1].  As this is a transitive dependency should we wait for the issue to be fixed in their `1.3` branch?

- [1] https://github.com/opensearch-project/OpenSearch-Dashboards/blob/5516d61ac6a3d08a2344fb64ff8a0128adc8008f/package.json#L420

**Comment by RyanL1997** [comment]
Closing this one, since the latest CVE fix for 1.3 branch has removed the `json5` dependency: https://github.com/opensearch-project/security-dashboards-plugin/pull/1308

**Pull request closed without merging**
