### PR TITLE
[BUG-1427] Newly created user defaults to same tenant as admin when using same browser window.

### PR DESCRIPTION
**Pull request by prabhask5**
### Description
Fixes bug that defaults a new user to the Global tenant, even when they do not have permission for the Global tenant and this option is blocked out on the modal. To fix this, I added new checks to the resolveTenantName function that checks whether the global and/or private tenants are disabled and goes through the available tenant options until it finds one that is not disabled.

### Category
Bug fix

### Why these changes are required?
New users were having the Global tenant role even when they don't have the permissions to, which is a security risk.

### What is the old behavior before changes and new behavior after changes?
Old behavior: When you select global tenant on the admin account then switch to a new user, this global tenant is selected by default even when this option is not available since the new user doesn't have access to the Global tenant.
Screenshot 2023-10-18 at 12 40 40 AM

New behavior: In this case, the default option automatically switches to the next accessible role, which is the Private tenant.
Screenshot 2023-10-18 at 12 52 10 AM

### Issues Resolved
Fixed issue #1427 

### Testing
Manually tested to make sure nothing was broken. Additionally added new tests to tenant-utils.test.tsx to update function and test for cases where the global tenant is not enabled.

### Check List
- [x] New functionality includes testing
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prabhask5** [comment]
Copying main comment from prev PR


> > @prabhask5 I have a few general questions.
> > 
> > 1. I think its possible that cluster admins can disable the private tenant. In that case how will this PR handle that scenario?
> > 2. Is it ever possible that a user has access to 0 tenants? If so, what is the behavior?
> > 3. If private or global are disabled does this PR resort to the first tenant for which the user has access?
> 
> @cwperks I'm not sure on what conditions the global and private tenants are disabled- does this depend on the data in the accountInfo tenantsList or does it depend on other info (either the config global disabled properties or the readonly roles), or both?
> 
> I'm also not sure if there's ever a scenario where there is access to 0 tenants- in my new changes I'm allowing the function to return an empty string for tenant, but when I try to do this on my local build that part doesn't work properly- so I'm assuming this can't happen?

For additional info, currently I'm using the following checks to see if the global and private tenants are disabled respectively:

`const isGlobalEnabled = config.multitenancy.tenants.enable_global;`
`const shouldDisableGlobal = !isGlobalEnabled || !tenants.includes('global_tenant');`

`const isPrivateEnabled = dashboardsInfo.private_tenant_enabled;`
`const shouldDisablePrivate = !isPrivateEnabled || !tenants.includes(userName) || readonly;`

But this is causing some tests to fail as they don't have the private and global tenants in the accountInfo tenants list so this util function thinks they are disabled when they are not. Am I wrong or are the tests wrong?

**Comment by cwperks** [comment]
@prabhask5 Do you have a list of tests where you are encountering the error? Its possible that more data would need to be mocked.

I have not been able to take a deep dive, but I'm looking at the code path and let me know what you think. I see that there is a default set in this [line](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/apps/account/tenant-switch-panel.tsx#L106) to `'' - i.e. global tenant` if there is no user requested tenant. In that same file I believe that the data structure returned from [accountInfo.data.tenants](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/apps/account/tenant-switch-panel.tsx#L94) contains the list of tenants the user has access to even if they are configured to be disabled.

Is it possible to filter that data structure to remove disabled tenants and then update the default [here](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/apps/account/tenant-switch-panel.tsx#L106) to take the first value from the list?

In the case where the `tenants` list is empty after filtering out the disabled tenants, is it possible to default to `''` even if the global tenant is disabled, but disable all buttons and display an alert with text around contacting the cluster administrator to provision access to the logged in user to a tenant so they can start using dashboards?

**Comment by prabhask5** [comment]
@cwperks With my current changes, all the tests in tenants-utils.test.tsx fail because of this error.

**Comment by davidlago** [comment]
@prabhask5 , please take a look at @cwperks 's comment above (also this PR has become stale and it needs a rebase). If you are not ready to continue with this PR at this time, we can close and re-open at a later time. Thanks!

**Pull request closed without merging**
