### PR TITLE
Adds system index permission as allowed action under static drop down list

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description
At present, the allowed action `system:admin/system_index` is not visible in the static drop down list and hence is not available to be assigned to a role. This PR adds that capability

### Category
Bug fix

### Issues Resolved
- Resolves https://github.com/opensearch-project/security-dashboards-plugin/issues/1697

### Testing

- [x] Should be present in Index permissions:
Screenshot 2023-12-13 at 6 14 12 PM

- [x] Should not be present in cluster permissions:
Screenshot 2023-12-13 at 6 16 28 PM

### Check List
- [x] New functionality includes testing
~- [ ] New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by derek-ho — APPROVED** [review]

**Review by derek-ho — APPROVED** [review]
Do we want to separate out the two functionality? It seems like this is packaging the index permission with some of the admin:admin work, but I am generally ok with this as is

**Comment by DarshitChanpura** [comment]
> Do we want to separate out the two functionality? It seems like this is packaging the index permission with some of the admin:admin work, but I am generally ok with this as is

Its a relatively small change, and should be okay to merge.

**Comment by peternied** [comment]
> Do we want to separate out the two functionality? It seems like this is packaging the index permission with some of the admin:admin work, but I am generally ok with this as is

Lets separate the permissions changes from the default password changes.  The additional permissions option doesn't seem time sensitive and it would be good to make a clear PR / commit when we've been changing how passwords are handled.

**Review by peternied — CHANGES_REQUESTED** [review]
> Do we want to separate out the two functionality? It seems like this is packaging the index permission with some of the admin:admin work, but I am generally ok with this as is

Lets separate the permissions changes from the default password changes.  The additional permissions option doesn't seem time sensitive and it would be good to make a clear PR / commit when we've been changing how passwords are handled.

**Review by cwperks — APPROVED** [review]

**Pull request merged**
