### PR TITLE
1203 Updated to add the tenant into the short URL once the short URL is resolved

### PR DESCRIPTION
**Pull request by leanneeliatra**
### Description
When the tenancy is being changed after copying a short URL, if the user then pastes this short URL into a new tab, the user will be redirected to the current selected tenant, not the tenant as specified in the copied short URL. 
We need to retain this information in the URL and redirect so the user is brought to the correct link, with the correct user.

### Category
[Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation]

### Why these changes are required?
To enable sharing of a short URL with the tenant as specified in the URL remaining selected as the active tenant.

### What is the old behavior before changes and new behavior after changes?
The old behaviour is: 
1. A short URL is copied (tenant is specified in the URL)
2. The tenant is changed
3. The link is loaded in a new tab
4. The tenant remains as is specified in 2, not as we would want/expect it to be as per the URL 
The new behaviour is: 
1. A short URL is copied (tenant is specified in the URL)
2. The tenant is changed
3. The link is loaded in a new tab
4. The link is loaded with tenant info retained.

### Issues Resolved
[[BUG] Shortlinks to other Tenants do not work #1203](https://github.com/opensearch-project/security-dashboards-plugin/issues/1203)

### Testing
Submitting the PR for an initial review of changes, tests will follow.

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by davidlago** [comment]
Thanks for the contribution, @leanneeliatra! PRs need to be made into `main`, please switch the target branch.

**Comment by leanneeliatra** [comment]
> Thanks for the contribution, @leanneeliatra! PRs need to be made into `main`, please switch the target branch.
Thank you @davidlago, done.

**Comment by DarshitChanpura** [comment]
Hello @leanneeliatra thank you for opening this PR. Would you please rebase your branch with latest changes from main?

**Comment by leanneeliatra** [comment]
This PR has been moved to a branch that was created directly from main, the changes got a bit confusing and I thought that was a better solution & allowed for a cleaner copy of the changes with testing against main. Thanks.

**Comment by leanneeliatra** [comment]
This PR has been moved to a branch that was created directly from main, and a new PR created.
https://github.com/opensearch-project/security-dashboards-plugin/pull/1462
The changes got a bit confusing and I thought that was a better solution & allowed for a cleaner copy of the changes with testing against main. Thanks. 
cc @DarshitChanpura @davidlago

**Pull request closed without merging**
