### PR TITLE
[Backport 2.8] Fixing dynamic tenancy changes for issues 1412

### PR DESCRIPTION
**Pull request by cwperks**
Backport of https://github.com/opensearch-project/security-dashboards-plugin/pull/1419 to 2.8

### CODE REVIEW

**Review by RyanL1997 — APPROVED** [review]

**Comment by RyanL1997** [comment]
FYI: The prerequisite check will not block the merging.

**Review by scrawfor99 — APPROVED** [review]

**Review by DarshitChanpura — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Per @cwperks and @RyanL1997 this is a flaky test (12th run pss on this specific [PR](https://github.com/opensearch-project/security-dashboards-plugin/pull/1446)), which will be addressed in the next minor version.
* https://github.com/opensearch-project/security-dashboards-plugin/pull/1455

Merge now.

Thanks.

**Comment by RyanL1997** [comment]
Thanks @peterzhuamazon for the help on merging. Yes, this is a known flaky, and [this fix](https://github.com/opensearch-project/security-dashboards-plugin/pull/1461) has already planned to remove it for 2.8 branch

**Comment by peterzhuamazon** [comment]
> Thanks @peterzhuamazon for the help on merging. Yes, this is a known flaky, and [this fix](https://github.com/opensearch-project/security-dashboards-plugin/pull/1461) has already planned to remove it for 2.8 branch

Great thanks.

**Pull request merged**
