### PR TITLE
[Backport 1.x] Add the tenant into the short URL once the short URL is resolved (#1462)

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description
Manually backports https://github.com/opensearch-project/security-dashboards-plugin/commit/e9f95763a16f5e42247830ff6083af6ef7014e9b from #1462.

### Category
Bug fix

### Check List
~- [ ] New functionality includes testing~
~- [ ] New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
@DarshitChanpura Could you provide a reason why the manual backport was needed?

**Comment by DarshitChanpura** [comment]
> @DarshitChanpura Could you provide a reason why the manual backport was needed?

Yes. Auto backport to 1.x failed: https://github.com/opensearch-project/security-dashboards-plugin/pull/1462#issuecomment-1638212557

**Comment by peternied** [comment]
Could you provide details on what conflict had to be handled, should another backport be included for this change?

**Comment by DarshitChanpura** [comment]
Yes.

There was a conflict in `tenant_resolver.ts` import statements due to: 1. Change in the way `OpenSearchDashboardsRequest` is imported. 2. Introduction of new variables where some old variables were moved to `common/index.ts`

**Comment by cwperks** [comment]
Looks like either the branch rules are off for 1.x or that the workflows should be updated to reflect the checks that this is expecting. We should see if its possible to update the workflows.

**Comment by cwperks** [comment]
This PR and https://github.com/opensearch-project/security-dashboards-plugin/pull/1514 can now be rebased on 1.x. I don't see the button to update the branch.

**Review by cwperks — APPROVED** [review]

**Pull request merged**
