### PR TITLE
Add release notes for PR #953

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

Add release notes for PR #953

### CODE REVIEW

**Comment by cliu123** [comment]
@peterzhuamazon Is this PR still needed?

**Review by peternied — CHANGES_REQUESTED** [review]
This change is not approved for the 2.0.0-rc1 release. No update is needed to these release notes.

**Review by davidlago — APPROVED** [review]

**Review by cliu123 — CHANGES_REQUESTED** [review]
The PR #953 won't be a part of RC1. It has been postponed to GA instead.

**Comment by peternied** [comment]
Since this release note will be going into the GA notes, I'm going to recreate this PR in that location.  Thanks for the contribution @peterzhuamazon

**Pull request closed without merging**
