### PR TITLE
Revert "Remove MDS selector for tenancy tab"

### PR DESCRIPTION
**Pull request by derek-ho**
Reverts opensearch-project/security-dashboards-plugin#1937

Edit: Adding more context here. The reason for this revert is @kgcreative's comment here: https://github.com/opensearch-project/security-dashboards-plugin/issues/1933#issuecomment-2101742784. Ideally, this tab should have the picker locked to the local cluster to maintain the same look across the plugin. Core doesn't have any plan to implement this, so we will add this back, and call it a user mis-configuration if that decide to hide the local cluster. Since security plugin is more of an admin view, when they visit they should have local cluster enabled.

### CODE REVIEW

**Review by scrawfor99 — APPROVED** [review]
Looks fine but is there context here?

**Comment by DarshitChanpura** [comment]
Why are we reverting this?

**Comment by derek-ho** [comment]
> Why are we reverting this?

Added context in the description

**Review by DarshitChanpura — APPROVED** [review]

**Comment by DarshitChanpura** [comment]
Thank you for updating the description @derek-ho !

**Review by cwperks — APPROVED** [review]

**Comment by DarshitChanpura** [comment]
@derek-ho Can you check code-cov failures once to determine if any tests are necessary?

**Pull request merged**
