### PR TITLE
Adds flow-framework transport actions to the static dropdown list of cluster permissions

### LINKED ISSUE #1907: Add flow_framework transport action names to the static drop down list
Add the following transport action names added in [flow_framework](https://github.com/search?q=repo%3Aopensearch-project%2Fflow-framework%20TRANSPORT_ACTION_NAME_PREFIX&type=code) to the static drop down list of cluster permissions displayed when editing/creating a role.

```yml
  'cluster:admin/opensearch/flow_framework/workflow/create',
  'cluster:admin/opensearch/flow_framework/workflow/delete',
  'cluster:admin/opensearch/flow_framework/workflow/deprovision',
  'cluster:admin/opensearch/flow_framework/workflow/get',
  'cluster:admin/opensearch/flow_framework/workflow/provision',
  'cluster:admin/opensearch/flow_framework/workflow/search',
  'cluster:admin/opensearch/flow_framework/workflow_state/get',
  'cluster:admin/opensearch/flow_framework/workflow_state/search',
  'cluster:admin/opensearch/flow_framework/workflow_step/get'
```

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Category
Enhancement

### Why these changes are required?
To allow end user to utilize security plugin to permission flow-framework permissions seamlessly.

### Issues Resolved
- Resolves #1907 

### Check List
~- [ ] New functionality includes testing~
~- [ ] New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DarshitChanpura** [comment]
@amitgalitz Would you please review this?

**Comment by amitgalitz** [comment]
> @amitgalitz Would you please review this?

This looks good, thanks for adding!

**Review by amitgalitz — APPROVED** [review]

**Review by derek-ho — APPROVED** [review]
@DarshitChanpura can you add the corresponding backend PR as well for reference?

**Comment by amitgalitz** [comment]
backend PR: https://github.com/opensearch-project/security/pull/3851

**Review by peternied — APPROVED** [review]

**Pull request merged**
