### PR TITLE
Version bump to 1.3.7

### PR DESCRIPTION
**Pull request by rishabh6788**
Signed-off-by: Rishabh Singh <sngri@amazon.com>

### Description
Version bump to 1.3.7

### Category
[Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation]

### Issues Resolved
[List any issues this PR will resolve (Is this a backport? If so, please add backport PR # and/or commits #)]

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DarshitChanpura** [comment]
@rishabh6788 ITs check won't pass until security-1.3.7.0 artifact is available.

**Review by DarshitChanpura — APPROVED** [review]

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peternied** [comment]
This change was merged bypassing CI checks and the 1.3 branch is broken with this change.  I am not going to revert since it will need to be introduce later

**Comment by cwperks** [comment]
@peternied @DarshitChanpura There is another open PR that I would like to merge that was blocked by unavailability of 1.3.7 build - https://github.com/opensearch-project/security-dashboards-plugin/pull/1226

I had explicitly put the `ref` to 1.3.6 for integration tests to show it working and the integ tests passed. I switched this back to `1.3` and they are failing due to the same reason as this PR. Can we merge the other PR as well?

**Comment by peternied** [comment]
@cwperks I'd like a spotless build and test run since there is a lot more functionality going in with that PR.  The branch protection rules (now) enforce this, seems like builds are being attempted for 1.3.7 via https://build.ci.opensearch.org/job/distribution-build-opensearch/

Might be a good idea to ping the release channel for what is going on with this release

**Pull request merged**
