### PR TITLE
Bump version to 2.3.1

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>

### Description
Bump version to 2.3.1 to prepare for next patch

### Category
[Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation]

### Issues Resolved
[List any issues this PR will resolve (Is this a backport? If so, please add backport PR # and/or commits #)]

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — APPROVED** [review]

**Comment by peternied** [comment]
Note; still waiting on artifacts for 2.3.1 to be available via https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.3.1/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-security-2.3.1.0.zip

@gaiksaya please let me know if there is any follow up you'd like me to perform on this front.

**Comment by gaiksaya** [comment]
@peternied In that case I need to add security plugin to [2.3.1 manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.3.1/opensearch-2.3.1.yml). Please confirm.

**Comment by peternied** [comment]
Yup, security not being in the manifest is the source of this issue  - @gaiksaya can you take care of this?

**Comment by gaiksaya** [comment]
PR is up https://github.com/opensearch-project/opensearch-build/pull/2677
Thanks!

**Review by DarshitChanpura — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Pull request merged**
