### PR TITLE
 Use smaller and compressed varients of buttons and form components

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description
Replace instances of `EuiButton` that don't have an explicit sizing attribute to `EuiSmallButton*`.
Replace instances of `Eui<form elements>` that don't have density attributes to `EuiCompressed<form elements>`.

### Category
Enhancement

### Why these changes are required?
UX

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by derek-ho — APPROVED** [review]
LGTM, as long as tests pass

**Review by DarshitChanpura — COMMENTED** [review]
Changes look good to me @AMoo-Miki ! Is there an issue related to this change? Also, could you add before and after screenshot/video of this change?

**Comment by derek-ho** [comment]
Screenshot 2024-08-06 at 1 07 28 PM
Screenshot 2024-08-06 at 1 07 17 PM
Screenshot 2024-08-06 at 1 06 24 PM


Looks like it is just some minor UX changes, don't have any concerns with this change. @AMoo-Miki confirmed offline there is no open issue regarding this.

**Review by DarshitChanpura — COMMENTED** [review]
Thanks @AMoo-Miki !

**Pull request merged**
