### PR TITLE
Change 2.0-alpha1 to 2.0-rc1.

### PR DESCRIPTION
**Pull request by dblock**
Following https://github.com/opensearch-project/opensearch-build/pull/1863, change 2.0-alpha1 to 2.0-rc1.

### CODE REVIEW

**Comment by peternied** [comment]
This change is blocked on https://github.com/opensearch-project/security/pull/1764 being added to the distribution build.

**Comment by peternied** [comment]
@DarshitChanpura I'm going to be unavaliable for a bit, could you help patch this pull request with update to the build paths?  I made this one change without being able to verifiy it, https://github.com/opensearch-project/security/pull/1764/commits/7434ebc1d0bedf2e49059d4290cdf1c6aceb931f

We will need something similar done in this PR

**Comment by dblock** [comment]
Once there's a successful distribution rc1 build CI will turn green here, let's retry later today.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by cliu123** [comment]
Has OSD been bumped to rc1? https://github.com/opensearch-project/security-dashboards-plugin/blob/main/opensearch_dashboards.json#L4

**Comment by dblock** [comment]
> https://github.com/opensearch-project/security-dashboards-plugin/blob/main/opensearch_dashboards.json#L4

I believe so, updated.

**Review by cliu123 — APPROVED** [review]

**Comment by cliu123** [comment]
> > https://github.com/opensearch-project/security-dashboards-plugin/blob/main/opensearch_dashboards.json#L4
> 
> I believe so, updated.

Thanks! @dblock

**Comment by DarshitChanpura** [comment]
> > https://github.com/opensearch-project/security-dashboards-plugin/blob/main/opensearch_dashboards.json#L4
> 
> I believe so, updated.

@dblock I see that the version in the main branch is still `2.0.0`. https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/package.json#L14

Should this be updated? Please let me know if I'm missing something here.

**Review by DarshitChanpura — APPROVED** [review]

**Comment by dblock** [comment]
> > > https://github.com/opensearch-project/security-dashboards-plugin/blob/main/opensearch_dashboards.json#L4
> > 
> > 
> > I believe so, updated.
> 
> @dblock I see that the version in the main branch is still `2.0.0`. https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/package.json#L14
> 
> Should this be updated? Please let me know if I'm missing something here.

Ok, I don't know @kavilla ?

**Comment by peterzhuamazon** [comment]
> > > https://github.com/opensearch-project/security-dashboards-plugin/blob/main/opensearch_dashboards.json#L4
> > 
> > 
> > I believe so, updated.
> 
> @dblock I see that the version in the main branch is still `2.0.0`. https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/package.json#L14
> 
> Should this be updated? Please let me know if I'm missing something here.

In Core they just need verion=2.0.0 because they have another qualifier=rc1 passed during build.
To your plugin, you need to point to 2.0.0-rc1 as a whole.
Thanks.

**Comment by DarshitChanpura** [comment]
> > > > https://github.com/opensearch-project/security-dashboards-plugin/blob/main/opensearch_dashboards.json#L4
> > > 
> > > 
> > > I believe so, updated.
> > 
> > 
> > @dblock I see that the version in the main branch is still `2.0.0`. https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/package.json#L14
> > Should this be updated? Please let me know if I'm missing something here.
> 
> In Core they just need verion=2.0.0 because they have another version=2.0.0-rc1 passed during build. To your plugin, you need to point to 2.0.0-rc1 as a whole. Thanks.

Ah...got it...thank you @kavilla !

**Comment by peterzhuamazon** [comment]
@kavilla let me know if dashboards is like that.
It is a bit different from OS.
So I could be wrong here.

Thanks.

**Comment by peterzhuamazon** [comment]
After talking between @kavilla and @dblock we probably need to revert this PR as @kavilla suggest dashboards core still point to `2.0.0` and relies on jenkins to push `2.0.0-rc1`.

**Comment by peterzhuamazon** [comment]
Revert in #947

**Pull request merged**
