### PR TITLE
[1.3] Increment version to 1.3.14.0

### PR DESCRIPTION
**Pull request by cwperks**
### Description

Increment version to 1.3.14.0

### Category

Maintenance

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
> @opensearch-project/engineering-effectiveness Can someone create a min distro of core for 1.3.14?
> 
> https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.14/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-security-1.3.14.0.zip and https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.14/latest/windows/x64/zip/builds/opensearch/plugins/opensearch-security-1.3.14.0.zip are missing.

Hey! Looks like 1.13.14 manifest only contains OpenSearch for now https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.14/opensearch-1.3.14.yml
You can create a PR to add security and then I can re-run the build once that is merged!
Thanks!

**Comment by cwperks** [comment]
Oh I see, the main and 2.x branches are publishing snapshots to maven and the 1.3 branch is not publishing the snapshots. I will update the 1.3 branch to pull SNAPSHOTs from maven to build with.

**Comment by gaiksaya** [comment]
> Oh I see, the main and 2.x branches are publishing snapshots to maven and the 1.3 branch is not publishing the snapshots. I will update the 1.3 branch to pull SNAPSHOTs from maven to build with.

I don't believe that would work as publishing zip snapshots was started from 2.x version? @prudhvigodithi please correct if I am wrong.

**Comment by cwperks** [comment]
I'm going to raise a PR to add security to the manifest in the build repo.

**Comment by cwperks** [comment]
@gaiksaya I raised a PR on the build repo to add security to the manifest for 1.3.14: https://github.com/opensearch-project/opensearch-build/pull/4226

Thank you for the help! :)

**Review by zelinh — COMMENTED** [review]
I'm a little confused. Shall we first bump the version here in order to build `security-1.3.14` artifact? @gaiksaya

**Comment by zelinh** [comment]
> I'm a little confused. Shall we first bump the version here in order to build `security-1.3.14` artifact? @gaiksaya

NVM, just realize this is the security dashboards plugin. :D

**Comment by cwperks** [comment]
Opened up a [PR in OSD core](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5531) to increment the version to 1.3.14. This PR is blocked until OSD Core is incremented.

**Review by RyanL1997 — APPROVED** [review]

**Review by derek-ho — APPROVED** [review]

**Pull request merged**
