### PR TITLE
Increment version to 2.1.1.0

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Category
Maintenance

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cliu123** [comment]
@DarshitChanpura The integration tests failed. Would you please take a look?

**Review by peternied — CHANGES_REQUESTED** [review]
In the intergration tests, the OpenSearch Dashboards branch references needs to be changed from `2.x` to `2.1` otherwise the integration tests won't be able to run

**Review by peternied — APPROVED** [review]

**Comment by peternied** [comment]
Merging this change is blocked on https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1862 from the test failure logs:

`Plugin "securityDashboards" is only compatible with OpenSearch Dashboards version "2.1.1", but used OpenSearch Dashboards version is "2.1.0". (incompatible-version, /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/OpenSearch-Dashboards/plugins/security-dashboards-plugin/opensearch_dashboards.json)`

**Comment by kavilla** [comment]
Hello OpenSearch Dashboards core for 2.1 branch is 2.1.1 now, apologies for the delay.

**Pull request merged**
