### PR TITLE
Update URLs referencing old docs-beta site

### PR DESCRIPTION
**Pull request by cwperks**
### Description

Replaced URLs starting with `https://docs-beta.opensearch.org/docs/security` to start with `https://opensearch.org/docs/latest/security-plugin` and updates link to multi-tenancy documentation renamed in this PR: https://github.com/opensearch-project/documentation-website/pull/1786

### Category
[Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation]

Bug fix

### Issues Resolved

https://github.com/opensearch-project/security-dashboards-plugin/issues/1174

### Testing

Updated snapshots with old URLs

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cwperks** [comment]
If this change gets backported then URLs need to be updated to their version specific locations which may not be guaranteed to be accurate. Can this be backported while keeping `latest/` in the URL?

**Review by DarshitChanpura — DISMISSED** [review]

**Comment by peternied** [comment]
@shanilpa Could you take a look at these changes to confirm they are pointed where you'd like to see?

**Comment by shanilpa** [comment]
@cwperks Everything looks good, but there are a couple that are pointing to the wrong place. Here are some screenshots to help and links to where I think they should go. Happy to discuss further if needed.

01:
image

02:
image


01 and 02: Link to [Attribute based security](https://opensearch.org/docs/latest/security-plugin/access-control/document-level-security/#attribute-based-security). I think it should link to the [access control page](https://opensearch.org/docs/latest/security-plugin/access-control/index/) so they can get clarity on the concept and see if they would like to leverage it. Ideally we should have a link on that page from each concept to the part of the docs site that enables them to achieve this concept.

**Review by shanilpa — CHANGES_REQUESTED** [review]
@cwperks It looks like we might have to add in a new constant for an external link too: https://opensearch.org/docs/latest/security-plugin/access-control/index/

There are a couple of learn more links that reference the wrong constant therefore linking to the wrong pages.

For more context you can refer to [this comment in the PR](https://github.com/opensearch-project/security-dashboards-plugin/pull/1231#issuecomment-1331217585) or reach out and we can chat through it.

**Comment by cwperks** [comment]
@shanilpa The links have now been updated to point to https://opensearch.org/docs/latest/security-plugin/access-control/index/ for the Learn More links next to Backend Roles.

**Review by DarshitChanpura — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Pull request merged**
