### PR TITLE
2.x version bump to 2.5.0

### PR DESCRIPTION
**Pull request by RyanL1997**
### Description
 Increment the version on the 2.x branch to the next development iteration.
### Category
Maintenance
### Issues Resolved
* Related #1140 
### Check List
- [ ] ~New functionality includes testing~
- [ ] ~New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DarshitChanpura** [comment]
https://github.com/opensearch-project/opensearch-build/pull/2931 has been merged and security has been added to build manifest. We have to wait until a build run is triggered so the artifact is available.

**Comment by peternied** [comment]
@RyanL1997 Can you look into the integration test failure, is this an intermittent issue?

**Comment by cwperks** [comment]
@peternied @RyanL1997 and I looked into this earlier and it looks like its due to this issue: https://github.com/actions/runner-images/issues/6399

`ubuntu-latest` is now resolving to `ubuntu-22.04` instead of `ubuntu-20.04` and it did not have firefox pre-installed. There was a recent update to `ubuntu-22.04` to include firefox so this should be resolved later this week. There is also the option to install firefox explicitly using an action like this: [https://github.com/opensearch-project/security-dashboards-plugin/pull/1226/files#diff-65ae1168eecd2c82b28b52c8a2c[…]bfa781144b33f0d74909103d9R10-R15](https://github.com/opensearch-project/security-dashboards-plugin/pull/1226/files#diff-65ae1168eecd2c82b28b52c8a2c70866716e326bfa781144b33f0d74909103d9R10-R15)

**Review by DarshitChanpura — APPROVED** [review]

**Comment by RyanL1997** [comment]
Update: I have already added the driver fix of Selenium into this PR. The original fix on main is (#1229 ).

**Review by cwperks — APPROVED** [review]

**Pull request merged**
