### PR TITLE
[Manual backport 2.8] Adds the newly created admin api permissions to the static dropdown list (#1446)

### PR DESCRIPTION
**Pull request by RyanL1997**
### Description
Manual backport #1446 because the CI failed 7 times in a row due to the flaky test case of SAML.

### Issues Resolved
* Relate #1446 

### Reference
* Original PR in main #1426 

### Check List
- [ ] ~New functionality includes testing~
- [ ] ~New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by cwperks — APPROVED** [review]

**Comment by cwperks** [comment]
@RyanL1997 Do you think we should add the changes from this [PR](https://github.com/opensearch-project/security-dashboards-plugin/pull/1448) to this branch as well?

**Comment by RyanL1997** [comment]
@cwperks I think this one has been merged: https://github.com/opensearch-project/security-dashboards-plugin/pull/1449

**Comment by RyanL1997** [comment]
@opensearch-project/security 
Note: since the original PR was failing 12 times in a row... :( I created this manual backport PR. For the failing of Prerequisite Check, it just happened now, I think this is because the build of security plugin of version 2.8.0 is expired. However, since we are using maven snapshot for all the test cases, I think it is reasonable for us to remove this `Prerequisite Check` workflow.

**Comment by RyanL1997** [comment]
Update: I just removed the latest `Prerequisite Check` workflow

**Pull request closed without merging**
