### PR TITLE
Move tenant-related utils to common folder

### PR DESCRIPTION
**Pull request by cliu123**
### Description
[Describe what this change achieves]

### Category
[Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation] Refactoring

### Issues Resolved
[[List any issues this PR will resolve (Is this a backport? If so, please add backport PR # and/or commits #)]
](https://github.com/opensearch-project/security-dashboards-plugin/issues/1175)

### Testing
UT, IT, Cypress tests

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cliu123** [comment]
@kavilla Please test these changes with the build script and see if they unblock you. Thanks!

**Comment by cliu123** [comment]
@kavilla confirmed that this PR resolved the release build failures. Thanks for finding and bringing up this issue!
@opensearch-project/security Please review. Thanks!

**Comment by cwperks** [comment]
@cliu123 @kavilla Is it possible to add a new check to validate this as part of our CI?

**Review by cwperks — APPROVED** [review]

**Comment by RyanL1997** [comment]
> @cliu123 @kavilla Is it possible to add a new check to validate this as part of the CI?
Same question from me, if we can figure out a solution for check with our own build, that would also be helpful on create our own reusable CI workflow as this issue(#1156) mentioned.

**Comment by cliu123** [comment]
created an issue to track the follow-up action items: https://github.com/opensearch-project/security-dashboards-plugin/pull/1169

**Pull request merged**
