### PR TITLE
Dynamically compute OpenID redirectUri from proxy HTTP headers

### PR DESCRIPTION
**Pull request by jaycci**
### Description
The OpenID redirectURI can be dynamically computed from proxy HTTP headers (`X-Forwarded-*`) if its new specific parameter is turned on in the configuration file (`opensearch_security.openid.trust_dynamic_headers`).

### Category
Enhancement

### Why these changes are required?
My company hosts one Opensearch Dashboards shared by many users (with tenants). We have a federated IAM based on OpenID configuration. The Opensearch Dashboards is behind a reverse proxy. We have a specific URL for each client that points to the same Opensearch Dashboards, thus we need to set dynamically the redirectURI.

Opensearch Dashboards should have a new option allowing dynamic configuration of the redirectURI, based on information sent by a reverse proxy.

### What is the old behavior before changes and new behavior after changes?
* Old behavior: redirectURI is hardcoded in Opensearch Dashboards configuration file.
* New behavior: same as old behavior, plus redirectURI computed from `X-Forwarded-*` headers if new configuration option says so; default "no" to not break anything.

### Testing
manual testing:

|   | `trust_dynamic_headers`: `FALSE` | `trust_dynamic_headers`: `TRUE` |
|---|---|---|
| `base_redirect_url`: `UNDEF` | `scheme://host:port` | `X-Forwarded-Proto://X-Forwarded-Host` if defined in HTTP headers |
| `base_redirect_url`: "VALUE" | "VALUE" | "VALUE" |

### Check List
- [x] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

Documentation: I will document the new parameter in https://github.com/opensearch-project/documentation-website/blob/main/_security-plugin/configuration/openid-connect.md#configuration-parameters as soon as you are OK with my PR.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jaycci** [comment]
@peternied I've added the unit tests you asked me. Do not hesitate to ask me if I need to do anything else.

**Review by peternied — CHANGES_REQUESTED** [review]
Looks great, thanks for adding the tests.  I have just one more ask please create an issue so this new configuration is documented.  You can use this issue as a template https://github.com/opensearch-project/documentation-website/issues/494

Let me know if you need a hand with this

**Comment by jaycci** [comment]
@peternied For faster processing, I've directly created a PR on the documentation project: opensearch-project/documentation-website#499. Tell me know if it's OK or if I need to do anything else.

**Review by peternied — APPROVED** [review]
Thanks! Looks great

**Comment by peternied** [comment]
@opensearch-project/security Could we get another reviewer to take a look at this PR?

**Review by cliu123 — APPROVED** [review]

**Comment by pratikshavyas** [comment]
With Opensearch dashboards v2.2.1, On access of UI, redirection is not considering value set for server.basePath and opensearch_security.openid.base_redirect_url as it is redirecting to "/" after authentication with openid. 
Please check  if this bug is introduced as part of this change and it has impacted url routing.

**Pull request merged**
